services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        env_file: './server/api/.env'
        ports:
            - '5555:5555'
        environment:
            MONGO_URI: 'mongodb://mongo:27017/subscriptions_tracker'
        depends_on:
            - mongo
        restart: 'on-failure'

    bot:
        build:
            context: .
            dockerfile: Dockerfile.bot
        env_file:
            - './bot/.env'
            - './.env'
        depends_on:
            - backend
            - mongo
        command:
            [
                'sh',
                '-c',
                'if [ -n "$VITE_WITH_TELEGRAM" ]; then python main.py; fi',
            ]

    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        ports:
            - '5173:80'
        env_file: './.env'
        environment:
            VITE_BACKEND_URL: 'http://backend:5555'
        depends_on:
            - backend
        restart: 'on-failure'

    mongo:
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - mongo_data:/data/db
        restart: 'on-failure'

volumes:
    mongo_data:
