FROM node:16-alpine

WORKDIR /app

COPY ./server/api/package*.json ./

RUN npm install

COPY ./server/api .

RUN npm run build

ENV NODE_ENV=production
ENV PORT=5173

EXPOSE 5173

CMD ["node", "--es-module-specifier-resolution=node", "index"]
